/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.actor.Unwatch');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.actor.PID');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.actor.Unwatch = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.actor.Unwatch, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.actor.Unwatch.displayName = 'proto.actor.Unwatch';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.actor.Unwatch.prototype.toObject = function(opt_includeInstance) {
  return proto.actor.Unwatch.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.actor.Unwatch} msg The msg instance to transform.
 * @return {!Object}
 */
proto.actor.Unwatch.toObject = function(includeInstance, msg) {
  var f, obj = {
    watcher: (f = msg.getWatcher()) && proto.actor.PID.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.actor.Unwatch}
 */
proto.actor.Unwatch.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.actor.Unwatch;
  return proto.actor.Unwatch.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.actor.Unwatch} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.actor.Unwatch}
 */
proto.actor.Unwatch.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.actor.PID;
      reader.readMessage(value,proto.actor.PID.deserializeBinaryFromReader);
      msg.setWatcher(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.actor.Unwatch.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.actor.Unwatch.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.actor.Unwatch} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.actor.Unwatch.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWatcher();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.actor.PID.serializeBinaryToWriter
    );
  }
};


/**
 * optional PID watcher = 1;
 * @return {?proto.actor.PID}
 */
proto.actor.Unwatch.prototype.getWatcher = function() {
  return /** @type{?proto.actor.PID} */ (
    jspb.Message.getWrapperField(this, proto.actor.PID, 1));
};


/** @param {?proto.actor.PID|undefined} value */
proto.actor.Unwatch.prototype.setWatcher = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.actor.Unwatch.prototype.clearWatcher = function() {
  this.setWatcher(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.actor.Unwatch.prototype.hasWatcher = function() {
  return jspb.Message.getField(this, 1) != null;
};


